### ISSUE TITLE
Failure to configure click

### ISSUE THREAD

**Issue by nderjung** [unikraft/lib-click#2]
:exclamation: **Pipeline [`click-staging`](https://concourse.unikraft.org/teams/apps/pipelines/click-staging)@[`9073779`](https://github.com/unikraft/app-click/tree/9073779626295abea92771268477edc184758992) / [`compile-click-kvm-x86_64`](https://concourse.unikraft.org/teams/apps/pipelines/click-staging/jobs/compile-click-kvm-x86_64) on task [`build`](https://concourse.unikraft.org/builds/26748) failed!**
```bash
[[37mINFO    [0m] checking whether __sync_synchronize supports arguments... no
[[37mINFO    [0m] checking for __has_trivial_copy... yes
[[37mINFO    [0m] checking for __thread storage class support... yes
[[37mINFO    [0m] checking for ffs... no
[[37mINFO    [0m] checking for ffsl... no
[[37mINFO    [0m] checking for ffsll... no
[[37mINFO    [0m] checking size of struct timeval... 0
[[37mINFO    [0m] checking for struct timespec... yes
configure: error: in `/tmp/build/80754af9/built/apps/click/build/libclick/origin/click-a5384835a6cac10f8d44da4eeea8eaa8f8e6a0c2':
configure: error: cannot compute sizeof (struct timespec)
See `config.log' for more details
[[37mINFO    [0m] checking size of struct timespec...   CP      config
make[1]: *** No rule to make target '/tmp/build/80754af9/built/apps/click/build/libclick/.configured', needed by '/tmp/build/80754af9/built/apps/click/build/libclick/.elementsmk'.  Stop.
make: *** [Makefile:984: sub-make] Error 2
[[37mINFO    [0m] make: Leaving directory '/tmp/build/80754af9/built/unikraft'
[[31mERROR   [0m] Command 'make -C /tmp/build/80754af9/built/unikraft A=/tmp/build/80754af9/built/apps/click P= L=/tmp/build/80754af9/built/libs/lwip:/tmp/build/80754af9/built/libs/newlib:/tmp/build/80754af9/built/libs/click prepare' returned 2

```
[View in Concourse](https://concourse.unikraft.org/builds/26748) | `fly i -b 26748 -s build`

_Issue created from a [Mattermost message](https://mattermost.nlehd.de/_redirect/pl/hwd4qpxzmpddxgggoho6yobm4c) *by @nderjung*._

**Comment by tbarbette** [comment]
Random google search lead me here. Config.log will probably show that the problem is not timespec, in click it's the first time a try_compile macro is used, so for instance in my machine the problem was "/usr/bin/ld: cannot find -lstdc++: No such file or directory", so actually LD_LIBRARY_PATH was missing. But maybe unikraft does not have libstdc++?

**Comment by nderjung** [comment]
Hi @tbarbette! This issue was created over 2 years ago, with a much older version of Unikraft and a much older build system.

We've been working hard to improve Unikraft over that time including auxiliary systems used to manage the build environment. I'll close this issue since it's no longer relevant.
